# Generated by Django 3.0.7 on 2020-07-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200613_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
